version: '3.8'
services:
  postgres:
    image: postgis/postgis:14-3.5
    restart: always
    environment:
      - POSTGRES_USER=test-user
      - POSTGRES_PASSWORD=test-password
      - POSTGRES_DB=test-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - node-postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test-user -d test-db']
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  server:
    build: ./server
    image: node:20-alpine
    volumes:
      - ./server:/app
    working_dir: /app
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - DATABASE_URL="postgresql://test-user:test-password@postgres:5432/test-db?schema=public"
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
    networks:
      - node-postgres
      - next-node

  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    depends_on:
      - postgres
      - server
    environment:
      - API_END_POINT=http://server:4000
      - NODE_ENV=development
    networks:
      - next-node

volumes:
  postgres:
networks:
  next-node:
  node-postgres:
